version: '3'

services:
  mysql:
    image: mysql:latest
    hostname: localhost
    restart: always
    environment:
      MYSQL_DATABASE: accountant
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: Root1
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/accountant
    ports:
      - "3307:3306"